# Commented lines that are ignored starte with the '#' mark.
## VF22S
# # A helpful tutorial for more information on make
# # https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all : main.c
	gcc -Wall -g main.c -o main

clean :
	rm main